# Generated by Django 3.0.3 on 2020-04-25 03:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='')),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
