# Generated by Django 3.0.3 on 2020-04-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
