# Generated by Django 3.0.3 on 2020-04-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200427_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publish_date']},
        ),
    ]
